/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.category;

import beans.Category;
import enums.CategoryType;
import bl.AusgabenBl;
import javax.swing.JOptionPane;
import javax.swing.tree.TreePath;

/**
 *
 * @author Bernhard
 */
public class CategoryManagementDlg extends javax.swing.JDialog {

    /**
     * Creates new form AddEditCategoryDlg
     */
    private AusgabenBl bl = AusgabenBl.getInstance();
    private CategoryTreeModel ctm;
    private Category selected = null;
    private CategoryType type;

    public CategoryManagementDlg(java.awt.Frame parent, boolean modal, boolean choosable, CategoryType type) {
        super(parent, modal);
        initComponents();
        
        this.type = type;
        
        if(type.equals(CategoryType.BILL)){
            ctm = new CategoryTreeModel(bl.getBillCategories());
        }else if(type.equals(CategoryType.DOCUMENT)){
            ctm = new CategoryTreeModel(bl.getDocumentCategories());
        }
        
        if(!choosable){
            remove(btOK);
            repaint();
        }
        
        jtCategories.setModel(ctm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCategories = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Übergeordnete Kategorie:"));

        jtCategories.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                onTreeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jtCategories);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton2.setText("Hinzufügen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddCategory(evt);
            }
        });

        jButton3.setText("Bearbeiten");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onUpdateCategory(evt);
            }
        });

        jButton4.setText("Löschen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteCategory(evt);
            }
        });

        btOK.setText("OK");
        btOK.setToolTipText("");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOK(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAddCategory(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddCategory
        String name = JOptionPane.showInputDialog(this, "Bitte Bezeichnung eingeben: ");
        if (name != null) {
            if (name.length() > 0 && selected != null) {
                if (!bl.doesSubCategoryExist(selected, name)) {
                    int level = selected.getLevel() + 1;
                    Category newCategory = new Category(name, selected, level, type);
                    bl.addObj(newCategory);
                    selected.getSubCategories().add(newCategory);
                    jtCategories.updateUI();
                } else {
                    JOptionPane.showMessageDialog(this, "Eine Sub-Kategorie mit dieser Bezeichnung exisitiert bereits!", "Fehler", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Bezeichnung ungültig oder keine Kategorie ausgwähltt!", "Fehler", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_onAddCategory

    private void onTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_onTreeValueChanged
        TreePath tp = evt.getNewLeadSelectionPath();
        if (tp != null) {
            Category cat = (Category) tp.getLastPathComponent();
            selected = cat;
        }
    }//GEN-LAST:event_onTreeValueChanged

    private void onUpdateCategory(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onUpdateCategory
        String name = JOptionPane.showInputDialog(this, "Bitte Bezeichnung eingeben: ", selected.getName());
        if (name.length() > 0 && selected != null) {
            selected.setName(name);
            bl.updateObj(selected);
            jtCategories.updateUI();
        } else {
            JOptionPane.showMessageDialog(this, "Bezeichnung ungültig oder keine Kategorie ausgwähltt!", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onUpdateCategory

    private void onDeleteCategory(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteCategory
        if (selected != null) {

            int sel = JOptionPane.showConfirmDialog(null, "ACHTUNG: Diese Aktion wird ALLE Kategorien sowie ALLE Unterkategorien löschen \n "
                    + "Fortfahren?");
            if (sel == JOptionPane.OK_OPTION) {
                if (!bl.isBillCategoryInUse(selected)) {
                    Category prior = selected.getPriorCategory();
                    prior.getSubCategories().remove(selected);
                    bl.removeObj(selected);
                    jtCategories.updateUI();
                } else {
                    JOptionPane.showMessageDialog(this, "Diese oder eine der Unterkategorien ist meiner Rechnung vernknüft "
                            + "und kann deshalb nicht gelöscht werden!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Es muss eine Kategorie ausgwählt werden!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onDeleteCategory

    private void onOK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOK
        // TODO add your handling code here:
    }//GEN-LAST:event_onOK

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryManagementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryManagementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryManagementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryManagementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CategoryManagementDlg dialog = new CategoryManagementDlg(new javax.swing.JFrame(), true, false, CategoryType.BILL);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOK;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jtCategories;
    // End of variables declaration//GEN-END:variables
}
