/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.constraintmanagement;

import beans.UserConstraint;
import enums.UserConstraintType;
import javax.swing.JOptionPane;

/**
 *
 * @author Bernhard1
 */
public class AddEditConstraintDlg extends javax.swing.JDialog {

    /**
     * Creates new form AddEditConstraintDlg
     */
    private boolean ok;
    private UserConstraint uc;

    public AddEditConstraintDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //set values for combobox
        cbTyp.removeAllItems();
        for (UserConstraintType uct : UserConstraintType.values()) {
            cbTyp.addItem(uct);
        }

        setSize(400, 150);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfKey = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbTyp = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tfValue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Bezeichnung:");
        getContentPane().add(jLabel1);
        getContentPane().add(tfKey);

        jLabel2.setText("Typ:");
        getContentPane().add(jLabel2);

        cbTyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbTyp);

        jLabel3.setText("Wert:");
        getContentPane().add(jLabel3);
        getContentPane().add(tfValue);

        jButton1.setText("Speichern");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSave(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("Abbrechen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSave
        String key = tfKey.getText();
        UserConstraintType type = (UserConstraintType) cbTyp.getSelectedItem();
        String value = tfValue.getText();

        if (key.length() > 0 && value.length() > 0) {
            if (type == UserConstraintType.DATE) {
                String parts[] = value.split("-");
                if (parts.length != 3) {
                    try {
                        for (String s : parts) {
                            int i = Integer.parseInt(s);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Wert oder Bezeichnung fehlerhaft!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Wert oder Bezeichnung fehlerhaft!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else if (type == UserConstraintType.FLOAT) {
                try {
                    value = value.replaceAll(";", ".");
                    float i = Float.parseFloat(value);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Wert oder Bezeichnung fehlerhaft!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else if (type == UserConstraintType.NUMERIC) {
                try {

                    int i = Integer.parseInt(value);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Wert oder Bezeichnung fehlerhaft!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            uc = new UserConstraint(key, value, type);
            ok = true;
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Wert oder Bezeichnung fehlerhaft!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onSave

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_onCancel

    public boolean isOk() {
        return ok;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditConstraintDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditConstraintDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditConstraintDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditConstraintDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEditConstraintDlg dialog = new AddEditConstraintDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbTyp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfKey;
    private javax.swing.JTextField tfValue;
    // End of variables declaration//GEN-END:variables
}
