/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.transfer;

import beans.Account;
import beans.Transfer;
import bl.AusgabenBl;
import gui.accounts.AccountManager;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Bernhard
 */
public class AddEditTransferDlg extends javax.swing.JDialog {

    /**
     * Creates new form AddEditTransferDlg
     */
    private AusgabenBl bl = AusgabenBl.getInstance();
    private boolean ok;
    private Transfer transfer;

    public AddEditTransferDlg(java.awt.Frame parent, boolean modal, Transfer transfer) {
        super(parent, modal);
        initComponents();

        updateAccounts(cbFrom);
        updateAccounts(cbTo);

        setSize(500, 200);
        setLocationRelativeTo(parent);
        
        if(transfer != null){
            cbFrom.setSelectedItem(transfer.getFrom().getName());
            cbTo.setSelectedItem(transfer.getTo().getName());
            tfValue.setText(transfer.getAbsolutValue().doubleValue() + "");
            dpDate.setDate(transfer.getDate());
            this.transfer = transfer;
        }
    }

    private void updateAccounts(JComboBox cbAccounts) {
        cbAccounts.removeAllItems();
        cbAccounts.addItem("---");
        for (Account acc : bl.getAccounts()) {
            cbAccounts.addItem(acc.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbFrom = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbTo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tfValue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dpDate = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Von: ");
        getContentPane().add(jLabel1);

        cbFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbFrom);

        jLabel2.setText("Nach: ");
        getContentPane().add(jLabel2);

        cbTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbTo);

        jLabel3.setText("Betrag: ");
        getContentPane().add(jLabel3);
        getContentPane().add(tfValue);

        jLabel4.setText("Datum:");
        getContentPane().add(jLabel4);
        getContentPane().add(dpDate);

        jButton1.setText("Speichern");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSave(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("Abbrechen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        getContentPane().add(jButton2);

        jMenu1.setText("Administrieren");

        jMenuItem1.setText("Konten");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAdminAccounts(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSave
        String fromStr = (String) cbFrom.getSelectedItem();
        String toStr = (String) cbTo.getSelectedItem();

        if (!fromStr.startsWith("-") && !toStr.startsWith("-")) {
            if (!fromStr.equalsIgnoreCase(toStr)) {
                Date date = dpDate.getDate();
                if (date != null) {
                    java.sql.Date newDate = new java.sql.Date(date.getTime());
                    String valueStr = tfValue.getText();
                    valueStr = valueStr.replaceAll(",", ".");
                    try {
                        BigDecimal value = new BigDecimal(valueStr);
                        Account from = bl.getAccountByName(fromStr);
                        Account to = bl.getAccountByName(toStr);
                        if(transfer == null)
                            transfer = new Transfer(from, to, value, newDate);
                        else
                            transfer.setData(from, to, value, newDate);
                        ok = true;
                        setVisible(false);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Der Betrag ist ungültig!", "Fehler", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Es muss ein Datum ausgewählt werden", "Fehler", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Es müssen zwei verscheidene Konton ausgewählt werden!", "Fehler", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Es müssen Konton ausgewählt werden!", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onSave

    private void onAdminAccounts(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAdminAccounts
        AccountManager am = new AccountManager(null, true);
        am.setVisible(true);
        updateAccounts(cbFrom);
        updateAccounts(cbTo);
        setVisible(false);
    }//GEN-LAST:event_onAdminAccounts

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_onCancel

    public boolean isOk() {
        return ok;
    }

    public Transfer getTransfer() {
        return transfer;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditTransferDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditTransferDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditTransferDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditTransferDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEditTransferDlg dialog = new AddEditTransferDlg(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbFrom;
    private javax.swing.JComboBox cbTo;
    private org.jdesktop.swingx.JXDatePicker dpDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField tfValue;
    // End of variables declaration//GEN-END:variables
}
